hp-bar:
  pattern: "&x&C&8&C&8&C&8[{lvl}lvl.] &x&A&3&F&F&C&E{name} &8| &x&F&F&8&4&8&4{health} ❤"
  bossbar:
    enabled: false
  customname:
    enabled: true
    time-to-mob-despawn: 120 # time in seconds if 0 = disabled.
    always-visible: false


multiplier: # percentage increase in damage/hp per level
  health: 10
  damage: 10

check-radius: 10 # radius checks to calculate mob strength
spawner-detect: true # spawners detect
# if enabled, then mobs from the spawner will have special spawn conditions
# mobs will spawn at the maximum level for the strongest RPG player around
# this will also work for the endermen farm

spawn-reasons: # reasons for spawning that we track and strengthen the mob
  - "NATURAL"
  - "JOCKEY"
  - "SPAWNER"
  - "EGG"
  - "SPAWNER_EGG"
  - "LIGHTNING"
  - "BUILD_SNOWMAN"
  - "BUILD_IRONGOLEM"
  - "BUILD_WITHER"
  - "VILLAGE_DEFENSE"
  - "VILLAGE_INVASION"
  - "BREEDING"
  - "SLIME_SPLIT"
  - "REINFORCEMENTS"
  - "NETHER_PORTAL"
  - "DISPENSE_EGG"
  - "INFECTION"
  - "CURED"
  - "OCELOT_BABY"
  - "SILVERFISH_BLOCK"
  - "MOUNT"
  - "TRAP"
  - "ENDER_PEARL"
  - "SHOULDER_ENTITY"
  - "DROWNED"
  - "SHEARED"
  - "EXPLOSION"
  - "RAID"
  - "PATROL"
  - "BEEHIVE"
  - "PIGLIN_ZOMBIFIED"
  - "COMMAND"
  - "CUSTOM"
  - "DEFAULT"

mobs:
  blaze: Blaze
  cave_spider: Cave spider
  creeper: Creeper
  enderman: Enderman
  endermite: Endermite
  evoker: Evoker
  evoker_fangs: Evoker_fangs
  ghast: Ghast
  giant: Giant
  guardian: Guardian
  husk: Husk
  illusioner: Illusioner
  piglin: Piglin
  hoglin: Hoglin
  shulker: Shulker
  silverfish: Silverfish
  skeleton: Skeleton
  slime: Slime
  spider: Spider
  vex: Vex
  vindicator: Vindicator
  witch: Witch
  wither_skeleton: Wither skeleton
  zombie: Zombie
  drowned: Drowned
  magma_cube: Magma cube
  piglin_brute: Piglin brute
  pillager: Pillager
  ravager: Ravager
  zombified_piglin: Zombified piglin
  zombie_villager: Zombie villager
  stray: Stray